### ISSUE TITLE
suggestions on C# SDK docs

### ISSUE THREAD

**Issue by longfeiWan9** [chenquanyu/neodocs#1]
看完文档以后，对照其他SDK的使用文档，我提了以下几个建议，可以参考一下：
1. 最开始缺少一个介绍的文档
   例如：C# SDK用来干嘛? 怎么使用? 整体结构是什么？有什么功能？
    可以参考一下：
    - [NEO SDK](https://docs.neo.org/docs/zh-cn/tooldev/sdk/introduction.html)
    - [neon-js getting started 部分](http://cityofzion.io/neon-js/docs/en/installation.html)
    - [neow3j overview 部分](https://neow3j.io/#/overview/getting_started)
2. 每一个文档开头的介绍，建议写的再详细一点。
    比如：
    - 主要用途是什么？
    - 包括什么功能？
    - 依赖的模块
    - 如果调用以后有反馈异常的，建议添加对异常返回的介绍
    - 等等
3. RPC 模块
    - 初始化的时候，建议介绍一个不同的网络
    - RPC接口过多，建议分模块的用表格先介绍一下 + 链接
    - RPC模块和monitor感觉有点重复，需要提供两个文档吗？还是考虑合并一下？
4. wallet 模块
    - 建议添加创建钱包、打开钱包、导出钱包这些介绍。
    - Claim GAS: 直接使用wif或者私钥作为参数？不需要用钱包来签名吗？
    - 重载的方法也详细解释一下各种用法
5. 合约模块 
   - 每个功能，建议拆分介绍每一个步骤，最后再汇总给一个sample. 
6. 交易模块
   - 建议首先抽象出一个概括的介绍，统一对构造tx的流程或者参数介绍一下；
   - 然后再举例说明每一个特殊案例，建议分拆每一步介绍

**Comment by chenquanyu** [comment]
1. 已经添加介绍文档
2. 每个文档添加了主要功能，在介绍中加入了异常介绍
3. 初始化介绍了测试网和本地节点，RPC文档作为一个详细列表，Monitor中添加了指向RPC的链接
4. wallet中添加了账户和钱包的基础介绍和操作
5. 已分拆介绍，删除了重复的sample
6. 添加了分步介绍

**Comment by longfeiWan9** [comment]
厉害！！！！！
